//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimRateSharp.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimRateSharp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Panel_SimRate => ResourceManager.GetString("Panel_SimRate", resourceCulture);
        internal static string Panel_GroundSpeed => ResourceManager.GetString("Panel_GroundSpeed", resourceCulture);
        internal static string Panel_AGL => ResourceManager.GetString("Panel_AGL", resourceCulture);
        internal static string Panel_Glide => ResourceManager.GetString("Panel_Glide", resourceCulture);
        internal static string Panel_Wind => ResourceManager.GetString("Panel_Wind", resourceCulture);
        internal static string Panel_Torque => ResourceManager.GetString("Panel_Torque", resourceCulture);

        internal static string Unit_Knots => ResourceManager.GetString("Unit_Knots", resourceCulture);
        internal static string Unit_KilometersPerHour => ResourceManager.GetString("Unit_KilometersPerHour", resourceCulture);
        internal static string Unit_MilesPerHour => ResourceManager.GetString("Unit_MilesPerHour", resourceCulture);
        internal static string Unit_Feet => ResourceManager.GetString("Unit_Feet", resourceCulture);
        internal static string Unit_Meters => ResourceManager.GetString("Unit_Meters", resourceCulture);
        internal static string Unit_Degrees => ResourceManager.GetString("Unit_Degrees", resourceCulture);

        internal static string Button_Reset => ResourceManager.GetString("Button_Reset", resourceCulture);

        internal static string Joystick_PressAnyButton => ResourceManager.GetString("Joystick_PressAnyButton", resourceCulture);
        internal static string Joystick_ButtonCaptured => ResourceManager.GetString("Joystick_ButtonCaptured", resourceCulture);

        internal static string Menu_Display => ResourceManager.GetString("Menu_Display", resourceCulture);
        internal static string Menu_Display_SimRate => ResourceManager.GetString("Menu_Display_SimRate", resourceCulture);
        internal static string Menu_Display_GroundSpeed => ResourceManager.GetString("Menu_Display_GroundSpeed", resourceCulture);
        internal static string Menu_Display_AGL => ResourceManager.GetString("Menu_Display_AGL", resourceCulture);
        internal static string Menu_Display_GlideSlope => ResourceManager.GetString("Menu_Display_GlideSlope", resourceCulture);
        internal static string Menu_Display_Wind => ResourceManager.GetString("Menu_Display_Wind", resourceCulture);

        internal static string Menu_Opacity => ResourceManager.GetString("Menu_Opacity", resourceCulture);

        internal static string Menu_PollingRate => ResourceManager.GetString("Menu_PollingRate", resourceCulture);
        internal static string Menu_PollingRate_250ms => ResourceManager.GetString("Menu_PollingRate_250ms", resourceCulture);
        internal static string Menu_PollingRate_500ms => ResourceManager.GetString("Menu_PollingRate_500ms", resourceCulture);
        internal static string Menu_PollingRate_750ms => ResourceManager.GetString("Menu_PollingRate_750ms", resourceCulture);
        internal static string Menu_PollingRate_1000ms => ResourceManager.GetString("Menu_PollingRate_1000ms", resourceCulture);
        internal static string Menu_PollingRate_2000ms => ResourceManager.GetString("Menu_PollingRate_2000ms", resourceCulture);

        internal static string Menu_JoystickDevice => ResourceManager.GetString("Menu_JoystickDevice", resourceCulture);
        internal static string Menu_Joystick_NoDevices => ResourceManager.GetString("Menu_Joystick_NoDevices", resourceCulture);
        internal static string Menu_Joystick_SelectDeviceFirst => ResourceManager.GetString("Menu_Joystick_SelectDeviceFirst", resourceCulture);
        internal static string Menu_Joystick_SetButton => ResourceManager.GetString("Menu_Joystick_SetButton", resourceCulture);
        internal static string Menu_Joystick_ButtonConfigured => ResourceManager.GetString("Menu_Joystick_ButtonConfigured", resourceCulture);
        internal static string Menu_Joystick_ChangeButton => ResourceManager.GetString("Menu_Joystick_ChangeButton", resourceCulture);
        internal static string Menu_Joystick_ClearButton => ResourceManager.GetString("Menu_Joystick_ClearButton", resourceCulture);

        internal static string Menu_TorqueLimiter => ResourceManager.GetString("Menu_TorqueLimiter", resourceCulture);
        internal static string Menu_TorqueLimiter_Enable => ResourceManager.GetString("Menu_TorqueLimiter_Enable", resourceCulture);
        internal static string Menu_TorqueLimiter_ShowDisplay => ResourceManager.GetString("Menu_TorqueLimiter_ShowDisplay", resourceCulture);
        internal static string Menu_TorqueLimiter_MaxTorque => ResourceManager.GetString("Menu_TorqueLimiter_MaxTorque", resourceCulture);
        internal static string Menu_TorqueLimiter_WarningThreshold => ResourceManager.GetString("Menu_TorqueLimiter_WarningThreshold", resourceCulture);
        internal static string Menu_TorqueLimiter_ReductionAggression => ResourceManager.GetString("Menu_TorqueLimiter_ReductionAggression", resourceCulture);
        internal static string Menu_TorqueLimiter_MinThrottle => ResourceManager.GetString("Menu_TorqueLimiter_MinThrottle", resourceCulture);
        internal static string Menu_TorqueLimiter_Cooldown => ResourceManager.GetString("Menu_TorqueLimiter_Cooldown", resourceCulture);
        internal static string Menu_TorqueLimiter_Interventions => ResourceManager.GetString("Menu_TorqueLimiter_Interventions", resourceCulture);

        internal static string Menu_Units => ResourceManager.GetString("Menu_Units", resourceCulture);
        internal static string Menu_Units_SpeedUnit => ResourceManager.GetString("Menu_Units_SpeedUnit", resourceCulture);
        internal static string Menu_Units_AltitudeUnit => ResourceManager.GetString("Menu_Units_AltitudeUnit", resourceCulture);
        internal static string Menu_Units_Speed_Knots => ResourceManager.GetString("Menu_Units_Speed_Knots", resourceCulture);
        internal static string Menu_Units_Speed_KMH => ResourceManager.GetString("Menu_Units_Speed_KMH", resourceCulture);
        internal static string Menu_Units_Speed_MPH => ResourceManager.GetString("Menu_Units_Speed_MPH", resourceCulture);
        internal static string Menu_Units_Altitude_Feet => ResourceManager.GetString("Menu_Units_Altitude_Feet", resourceCulture);
        internal static string Menu_Units_Altitude_Meters => ResourceManager.GetString("Menu_Units_Altitude_Meters", resourceCulture);

        internal static string Menu_Language => ResourceManager.GetString("Menu_Language", resourceCulture);
        internal static string Menu_Language_English => ResourceManager.GetString("Menu_Language_English", resourceCulture);
        internal static string Menu_Language_German => ResourceManager.GetString("Menu_Language_German", resourceCulture);
        internal static string Menu_Language_French => ResourceManager.GetString("Menu_Language_French", resourceCulture);
        internal static string Menu_Language_Chinese => ResourceManager.GetString("Menu_Language_Chinese", resourceCulture);
        internal static string Menu_Language_Spanish => ResourceManager.GetString("Menu_Language_Spanish", resourceCulture);
        internal static string Menu_Language_RestartRequired => ResourceManager.GetString("Menu_Language_RestartRequired", resourceCulture);
        internal static string Menu_Language_RestartTitle => ResourceManager.GetString("Menu_Language_RestartTitle", resourceCulture);

        internal static string Menu_About => ResourceManager.GetString("Menu_About", resourceCulture);
        internal static string Menu_Exit => ResourceManager.GetString("Menu_Exit", resourceCulture);

        internal static string About_Title => ResourceManager.GetString("About_Title", resourceCulture);
        internal static string About_Subtitle => ResourceManager.GetString("About_Subtitle", resourceCulture);
        internal static string About_Description => ResourceManager.GetString("About_Description", resourceCulture);
        internal static string About_ViewOnGitHub => ResourceManager.GetString("About_ViewOnGitHub", resourceCulture);
        internal static string About_Close => ResourceManager.GetString("About_Close", resourceCulture);

        internal static string Dialog_MaxTorque_Title => ResourceManager.GetString("Dialog_MaxTorque_Title", resourceCulture);
        internal static string Dialog_MaxTorque_Prompt => ResourceManager.GetString("Dialog_MaxTorque_Prompt", resourceCulture);
        internal static string Dialog_WarningThreshold_Title => ResourceManager.GetString("Dialog_WarningThreshold_Title", resourceCulture);
        internal static string Dialog_WarningThreshold_Prompt => ResourceManager.GetString("Dialog_WarningThreshold_Prompt", resourceCulture);
        internal static string Dialog_ReductionAggression_Title => ResourceManager.GetString("Dialog_ReductionAggression_Title", resourceCulture);
        internal static string Dialog_ReductionAggression_Prompt => ResourceManager.GetString("Dialog_ReductionAggression_Prompt", resourceCulture);
        internal static string Dialog_MinThrottle_Title => ResourceManager.GetString("Dialog_MinThrottle_Title", resourceCulture);
        internal static string Dialog_MinThrottle_Prompt => ResourceManager.GetString("Dialog_MinThrottle_Prompt", resourceCulture);
        internal static string Dialog_Cooldown_Title => ResourceManager.GetString("Dialog_Cooldown_Title", resourceCulture);
        internal static string Dialog_Cooldown_Prompt => ResourceManager.GetString("Dialog_Cooldown_Prompt", resourceCulture);

        internal static string Error_FatalError => ResourceManager.GetString("Error_FatalError", resourceCulture);
        internal static string Error_ApplicationError => ResourceManager.GetString("Error_ApplicationError", resourceCulture);
        internal static string Error_UnhandledException => ResourceManager.GetString("Error_UnhandledException", resourceCulture);
        internal static string Error_JoystickDevice => ResourceManager.GetString("Error_JoystickDevice", resourceCulture);
        internal static string Error_JoystickTitle => ResourceManager.GetString("Error_JoystickTitle", resourceCulture);
        internal static string Error_BrowserOpen => ResourceManager.GetString("Error_BrowserOpen", resourceCulture);
        internal static string Error_Title => ResourceManager.GetString("Error_Title", resourceCulture);
    }
}
